/**
 * Dedicated AI Generation Detector Service for Documents & Text Content
 * Evaluates explicit self-disclosures, synthetic content declarations, document metadata,
 * and stylometric language heuristics using a hybrid heuristic approach.
 */
class AiGenerationDetector {
  /**
   * Explicit AI Disclosure Patterns
   * Matches statements where a document explicitly declares that it is AI-generated.
  /**
   * Explicit AI Tool / Generator Disclosure Patterns
   * Strong evidence: Matches statements where a document explicitly declares that it was generated by an AI tool or system.
   */
  static AI_TOOL_DISCLOSURE_PATTERNS = [
    /\b(?:generated|created|written|produced|authored|crafted|drafted)\s+(?:entirely\s+|completely\s+|partially\s+)?(?:by|using|with)\s+(?:ai|artificial\s+intelligence|chatgpt|gpt-?4|claude|gemini|copilot|midjourney|dall-e|llm|large\s+language\s+model)\b/i,
    /\b(?:ai-generated|ai\s+generated|created\s+by\s+ai|written\s+by\s+ai|produced\s+by\s+artificial\s+intelligence)\b/i,
    /\bthis\s+document\s+is\s+(?:an?\s+)?(?:ai-generated|ai\s+generated)\b/i,
    /\b(?:created|generated)\s+for\s+(?:trustgraph\s+ai|ai\s+testing)\s+by\s+(?:ai|artificial\s+intelligence|llm)\b/i,
    /\b(?:fictional\s+data|synthetic\s+document|synthetic\s+data)\s+(?:generated|created)\s+by\s+ai\b/i,
  ];

  // Backward compatibility alias
  static EXPLICIT_DISCLOSURE_PATTERNS = this.AI_TOOL_DISCLOSURE_PATTERNS;

  /**
   * Generic Synthetic / Demonstration Language Patterns (Normal Document Language)
   * Weak/zero AI evidence: Common in QA documents, mock interview projects, test plans, contracts, and educational materials.
   * MUST NOT independently produce detected = true.
   */
  static GENERIC_SYNTHETIC_PATTERNS = [
    /\b(?:fictional|synthetic|sample)\s+(?:organization|company|corporation|entity|dataset|data|report|review\s+period|project|case\s+study|example)\b/i,
    /\bdoes\s+not\s+(?:describe|represent)\s+a\s+real\s+(?:organization|company|person|entity|event)\b/i,
    /\bfor\s+(?:demonstration|testing|sample|qa|evaluation|training)\s+purposes?\s+only\b/i,
    /\b(?:sample\s+document|mock\s+(?:interview|project|dataset|data)|test\s+plan|qa\s+guide)\b/i,
    /\ball\s+(?:data|names|figures)\s+(?:are|is)\s+(?:fictional|synthetic|simulated)\b/i,
  ];

  // Retain reference for any external callers
  static SYNTHETIC_CONTENT_PATTERNS = this.GENERIC_SYNTHETIC_PATTERNS;

  /**
   * AI Mention Context Patterns (Subject Matter, NOT Self-Disclosure)
   * e.g., "AI is transforming healthcare" or "use of artificial intelligence in business"
   */
  static AI_SUBJECT_PATTERNS = [
    /\b(?:use|impact|role|growth|future|adoption|development|field|market|research)\s+of\s+(?:ai|artificial\s+intelligence)\b/i,
    /\b(?:ai|artificial\s+intelligence)\s+(?:in|for|is|will|can|has|technologies|solutions|tools)\b/i,
  ];

  /**
   * Canonical AI Transition Phrases (Secondary Stylometric Signals)
   */
  static STYLOMETRIC_AI_PHRASES = [
    'in conclusion',
    'furthermore',
    'it is important to note',
    'delve into',
    'testament to',
    'tapestry of',
    'seamlessly',
    'pivotal role',
    'beacon of',
    'vital to understand',
    'overall performance',
    'strategic alignment',
  ];

  /**
   * Master AI Generation Detection Pipeline
   */
  static detectAiGeneration(text = '', metadata = {}) {
    const textLower = text.toLowerCase();
    const signals = [];

    let likelihood = 0.05;
    let confidence = 0.70;

    // 1. Check for Explicit AI Tool / Generator Disclosures (Strongest Signal)
    let hasExplicitDisclosure = false;
    let disclosureMatchText = '';

    for (const pattern of this.AI_TOOL_DISCLOSURE_PATTERNS) {
      const match = text.match(pattern);
      if (match) {
        hasExplicitDisclosure = true;
        disclosureMatchText = match[0];
        break;
      }
    }

    if (hasExplicitDisclosure) {
      likelihood = 0.99;
      confidence = 0.99;
      signals.push({
        type: 'AI_TOOL_DECLARATION',
        severity: 'very_high',
        confidence: 0.99,
        description: 'Document explicitly identifies itself as AI-generated by a known generative tool/system.',
        evidence: `Matched disclosure: "${disclosureMatchText}"`,
      });
      signals.push({
        type: 'explicit_ai_disclosure',
        severity: 'very_high',
        confidence: 0.99,
        description: 'Explicit AI tool attribution verified.',
        evidence: `Matched disclosure: "${disclosureMatchText}"`,
      });
    }

    // 2. Check for Generic Synthetic / Demonstration Language (Normal Document Context)
    // CRITICAL: Generic synthetic language MUST NOT independently produce detected = true
    let hasGenericSynthetic = false;
    let genericMatchText = '';

    for (const pattern of this.GENERIC_SYNTHETIC_PATTERNS) {
      const match = text.match(pattern);
      if (match) {
        hasGenericSynthetic = true;
        genericMatchText = match[0];
        break;
      }
    }

    if (hasGenericSynthetic) {
      signals.push({
        type: 'GENERIC_SYNTHETIC_LANGUAGE',
        severity: 'info',
        confidence: 0.85,
        description: 'Document contains standard sample, demonstration, or fictional disclaimer phrasing (common human QA/testing convention; not treated as AI generation).',
        evidence: `Matched phrasing: "${genericMatchText}"`,
      });
      // Do NOT raise likelihood or confidence. Remains normal human document baseline unless explicit AI tool is disclosed.
    }

    // 3. Check Document Metadata Signals (Phase 5)
    const creatorStr = `${metadata.creator || ''} ${metadata.author || ''} ${metadata.producer || ''}`.toLowerCase();
    const aiMetadataTool = ['chatgpt', 'openai', 'claude', 'midjourney', 'dall-e', 'langchain', 'auto-gpt'].find(
      (tool) => creatorStr.includes(tool)
    );

    if (aiMetadataTool) {
      if (!hasExplicitDisclosure) {
        likelihood = Math.max(likelihood, 0.80);
        confidence = Math.max(confidence, 0.85);
      }
      signals.push({
        type: 'AI_METADATA_SIGNATURE',
        severity: 'medium',
        confidence: 0.85,
        description: `Document metadata explicitly attributes creation software tool: "${aiMetadataTool}".`,
      });
      signals.push({
        type: 'metadata_signature',
        severity: 'medium',
        confidence: 0.85,
        description: `Document metadata explicitly attributes creation software tool: "${aiMetadataTool}".`,
      });
    }

    // 4. Stylometric & Vocabulary Signals (Phase 6 - Secondary/Limited Weight)
    const words = textLower.match(/\b[a-z']+\b/g) || [];
    let matchedPhrasesCount = 0;
    this.STYLOMETRIC_AI_PHRASES.forEach((phrase) => {
      if (textLower.includes(phrase)) matchedPhrasesCount++;
    });

    // Check sentence length variance (burstiness)
    const sentences = text.split(/[.!?]+/).map((s) => s.trim()).filter(Boolean);
    const sentenceLengths = sentences.map((s) => (s.match(/\b\w+\b/g) || []).length);
    const meanLen = sentenceLengths.reduce((a, b) => a + b, 0) / (sentenceLengths.length || 1);
    const variance = sentenceLengths.reduce((sq, n) => sq + Math.pow(n - meanLen, 2), 0) / (sentenceLengths.length || 1);
    const burstiness = Math.sqrt(variance);

    if (!hasExplicitDisclosure) {
      // Small likelihood bump for stylometric features
      if (matchedPhrasesCount >= 3) {
        likelihood += 0.10;
        signals.push({
          type: 'AI_STYLE_HEURISTIC',
          severity: 'low',
          confidence: 0.60,
          description: `Document uses multiple canonical transition patterns (${matchedPhrasesCount} phrases).`,
        });
      }

      if (burstiness < 4.0 && words.length > 50) {
        likelihood += 0.05;
        signals.push({
          type: 'AI_STYLE_HEURISTIC',
          severity: 'low',
          confidence: 0.55,
          description: 'Low sentence length variance across paragraphs.',
        });
      }
    }

    // 5. Subject-Matter Guard against False Positives (Phase 7)
    // If "AI" is mentioned as a subject without explicit self-disclosure, ensure likelihood remains low
    const isSubjectMatterMention = !hasExplicitDisclosure && this.AI_SUBJECT_PATTERNS.some((p) => p.test(text));
    if (isSubjectMatterMention && !aiMetadataTool) {
      likelihood = Math.min(likelihood, 0.20); // Clamp likelihood to low
    }

    // Clamp final values
    likelihood = Math.min(0.99, parseFloat(Math.max(0.01, likelihood).toFixed(2)));
    confidence = Math.min(0.99, parseFloat(Math.max(0.10, confidence).toFixed(2)));

    // Determine Classification
    let classification = 'LOW';
    if (likelihood >= 0.85) classification = 'VERY_HIGH';
    else if (likelihood >= 0.65) classification = 'HIGH';
    else if (likelihood >= 0.35) classification = 'MEDIUM';

    const detected = classification === 'VERY_HIGH' || classification === 'HIGH';

    // Summary Explanation
    let explanation = 'Document exhibits natural human writing characteristics and varied sentence structure.';
    if (hasExplicitDisclosure) {
      explanation = 'Document explicitly declares that it was generated by an AI tool or generative system.';
    } else if (hasGenericSynthetic) {
      explanation = 'Document exhibits human author characteristics with standard QA/demonstration sample phrasing.';
    } else if (classification === 'HIGH' || classification === 'MEDIUM') {
      explanation = 'Document contains elevated stylometric or structural features indicative of AI generation.';
    }

    return {
      detected,
      likelihood,
      confidence,
      classification,
      method: 'hybrid_heuristic',
      signals,
      explanation,
      limitations:
        'AI-generation detection is probabilistic based on explicit disclosures, metadata, and stylometric heuristics. It should not be treated as definitive proof.',
    };
  }
}

module.exports = AiGenerationDetector;
