const AiGenerationDetector = require('../../src/services/aiGenerationDetector');

describe('AiGenerationDetector Unit Tests', () => {
  describe('detectAiGeneration()', () => {
    it('should detect VERY_HIGH AI generation likelihood for explicit AI disclosures', () => {
      const text = `
        AI-Generated Operational Performance Report
        This document is generated by AI and contains fictional data created for TrustGraph testing.
        All metrics describe a synthetic organization.
      `;

      const result = AiGenerationDetector.detectAiGeneration(text, { creator: 'Synthetic AI Generator' });

      expect(result.detected).toBe(true);
      expect(result.likelihood).toBe(0.99);
      expect(result.confidence).toBe(0.99);
      expect(result.classification).toBe('VERY_HIGH');
      expect(result.signals.some((s) => s.type === 'explicit_ai_disclosure')).toBe(true);
    });

    it('should NOT trigger VERY_HIGH likelihood when AI is merely mentioned as a subject in human text', () => {
      const text = `
        The Integration of Artificial Intelligence in Enterprise Security.
        This report discusses the use of AI in healthcare and financial institutions.
        Companies adoption of AI technology is growing rapidly.
      `;

      const result = AiGenerationDetector.detectAiGeneration(text, { creator: 'Human Author' });

      expect(result.classification).toBe('LOW');
      expect(result.likelihood).toBeLessThan(0.35);
      expect(result.signals.some((s) => s.type === 'explicit_ai_disclosure')).toBe(false);
    });

    it('should detect synthetic content declarations', () => {
      const text = `
        Quarterly Operations Review.
        This report uses a synthetic dataset and describes a fictional organization for demonstration.
      `;

      const result = AiGenerationDetector.detectAiGeneration(text);

      expect(result.detected).toBe(true);
      expect(result.likelihood).toBeGreaterThanOrEqual(0.75);
      expect(result.signals.some((s) => s.type === 'synthetic_content')).toBe(true);
    });

    it('should handle empty or minimal text gracefully', () => {
      const result = AiGenerationDetector.detectAiGeneration('');

      expect(result.classification).toBe('LOW');
      expect(result.likelihood).toBeLessThan(0.20);
    });

    it('should identify AI metadata signatures', () => {
      const text = 'Standard corporate quarterly review with diverse sentence rhythm and structure.';
      const metadata = { creator: 'ChatGPT PDF Exporter' };

      const result = AiGenerationDetector.detectAiGeneration(text, metadata);

      expect(result.signals.some((s) => s.type === 'metadata_signature')).toBe(true);
      expect(result.likelihood).toBeGreaterThanOrEqual(0.80);
    });
  });
});
